### ISSUE TITLE
Consolidate database, s3, hdfs into top-level cluster config

### ISSUE THREAD

**Issue by maltesander** [stackabletech/hive-operator#291]
Part of https://github.com/stackabletech/issues/issues/293

The database currently can be specified on role and role-group level.

This does not make sense since all cluster pods should connect to the same database.

## TODO:
- [x] Create top-level `clusterConfig`
- [x] Move `database` from `MetastoreConfig` to `clusterConfig`
- [x] Move top-level `s3`, `hdfs` and `serviceType` to `clusterConfig`
- [x] Adapt docs 
- [x] Adapt tests
