### ISSUE TITLE
Add mysql jdbc driver to docker image

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/hive-operator#415]
In https://docs.stackable.tech/home/stable/hive/required-external-components we list mysql as supported
`helm install mysql oci://registry-1.docker.io/bitnamicharts/mysql --set auth.database=hive --set auth.username=hive --set auth.password=hive`
```
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hms-mysql
spec:
  image:
    productVersion: 3.1.3
    stackableVersion: 0.0.0-dev
  clusterConfig:
    database:
      connString: jdbc:mysql://mysql:6033/hive
      user: hive
      password: hive
      dbType: mysql
  metastore:
    roleGroups:
      default:
        replicas: 2
```
produces
```
2024-02-19T07:28:59,684 ERROR [main] tools.HiveSchemaHelper: Unable to find driver class
java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:527) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:315) ~[?:?]
        at org.apache.hadoop.hive.metastore.tools.HiveSchemaHelper.getConnectionToMetastore(HiveSchemaHelper.java:85) [hive-exec-3.1.3.jar:3.1.3]
        at org.apache.hive.beeline.HiveSchemaTool.getConnectionToMetastore(HiveSchemaTool.java:169) [hive-beeline-3.1.3.jar:3.1.3]
        at org.apache.hive.beeline.HiveSchemaTool.doValidate(HiveSchemaTool.java:601) [hive-beeline-3.1.3.jar:3.1.3]
        at org.apache.hive.beeline.HiveSchemaTool.main(HiveSchemaTool.java:1522) [hive-beeline-3.1.3.jar:3.1.3]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.hadoop.util.RunJar.run(RunJar.java:323) [hadoop-common-3.3.3.jar:?]
        at org.apache.hadoop.util.RunJar.main(RunJar.java:236) [hadoop-common-3.3.3.jar:?]
org.apache.hadoop.hive.metastore.HiveMetaException: Failed to load driver
Underlying cause: java.lang.ClassNotFoundException : com.mysql.jdbc.Driver
```

```[tasklist]
### Tasks
- [ ] mysql driver version to use determined
- [ ] mysql driver added
- [ ] smoke test using mysql added
- [ ] Check if other supported drivers (such as Oracle or MS SQL) are included
```

**Comment by lfrancke** [comment]
MySQL has a license that we cannot or do not want to include in our images: https://downloads.mysql.com/docs/licenses/connector-j-8.3-com-en.pdf

We can however think about adding MariaDB instead.

**Comment by Jimvin** [comment]
The MariaDB JDBC driver is released under the LGPG license. https://mariadb.com/kb/en/about-mariadb-connector-j/

**Comment by lfrancke** [comment]
We will not be implementing this but we have [documented](https://docs.stackable.tech/home/nightly/hive/usage-guide/database-driver) what you can do to add your own drivers in https://github.com/stackabletech/hive-operator/issues/416
